# Uncomment the next line to define a global platform for your project
platform :ios, '15.0'
use_frameworks!

target 'LoaPalette' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for LoaPalette
  pod 'shared', :path => '../../shared'
  
  # Firebase
  pod 'Firebase/Analytics'
  pod 'Firebase/Crashlytics'
  pod 'Firebase/RemoteConfig'
  pod 'Firebase/Firestore'
  pod 'Firebase/Auth'
  
  # AdMob
  pod 'Google-Mobile-Ads-SDK'

end

