# Uncomment the next line to define a global platform for your project
platform :ios, '15.0'
use_frameworks!

target 'LorPalette' do

  # Pods for LorPalette
  # shared.podspecでFirebaseの依存関係を管理
  pod 'shared', :path => '../../shared'
  
  # Swiftコードから直接使用するため、FirebaseAnalyticsを追加
  pod 'FirebaseAnalytics', :modular_headers => true
  
  # Swiftコードから直接使用するため、GoogleSignInを追加
  pod 'GoogleSignIn', :modular_headers => true
  
  # Hot Reloading
  pod 'InjectHotReload', :modular_headers => true

  post_install do |installer|
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['SWIFT_VERSION'] = '5.0'
      end
    end
  end

end

